import "./globals.css";

import { Metadata } from "next";
import { Sarabun, Tajawal } from "next/font/google";

import Providers from "@/components/providers/Provider";

// Layouts
import Header from "@/components/layout/app/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const sarabun = Sarabun({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-sarabun",
});
const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  variable: "--font-tajawal",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${sarabun.variable} ${tajawal.variable} antialiased dark:bg-zinc-800 `}
      >
         {/* <Providers> */}
        {/* <Header /> */}
       {children}
       {/* </Providers> */}
      </body>
    </html>
  );
}
